### ISSUE TITLE
Command /bin/sh failed with exit code 1

### ISSUE THREAD

**Issue by Esqarrouth** [johnno1962/unhide#1]
- '[' Debug = Debug ']'
- NORMAL_ARCH_FILE=/Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/Arcane
- LINK_FILE_LIST=/Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/Arcane.LinkFileList
- [[ /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Products/Debug-iphonesimulator/Arcane.app =~ .framework ]]
- VERSIONS='-Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs'
- echo 'Exporting any "hidden" Swift internal symbols in Arcane framework'
  Exporting any "hidden" Swift internal symbols in Arcane framework
  ++ dirname /Users/gok2/bin/unhide.sh
  ++ cat /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/Arcane.LinkFileList
- /Users/gok2/bin/unhide Arcane /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/main.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ProfileVC.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIApplicationExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/CardData.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/TypeFieldView.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/NSObjectExtentions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ACL.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneCardVC.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/LaunchVC.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/LoginVC.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/PostCard.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/NSDateExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIViewExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/CozyLoadingActivity.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneConfigs.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UILabelExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIScrollViewExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIViewControllerExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UserSession.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/SimulateNetwork.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneNotifications.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIColorExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/DummyVC.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneStyles.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/AuthorInfoView.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIFontExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/VCOrganizer.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcanePhotoKit.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/CommentData.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/CGPointExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ContentOrganizer.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/PostVC.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UITextViewExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ServerConnection.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIDeviceExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/TutorialLogic.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/LibraryList.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIImageExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/CemKit.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/DictionaryExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/MotherVC.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/CommentView.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/NSAttributedStringExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ToDoList.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UserData.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/TutorialCard.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/BreakMenu.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/AppDelegate.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/StringExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArrayExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/MainVC.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/MainCard.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/IntExtentions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIButtonExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneUserDefaults.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/BoolExtentions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/TutorialCardData.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneAnalytics.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/CGRectExtentions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneCardView.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIScreenExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/UIImageViewExtensions.o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/ArcaneColors.o
- echo 'Relinking with the patched object files'
  Relinking with the patched object files
- cd /Users/gok2/Documents/Arcane
- export PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
- PATH=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin
- /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Products/Debug-iphonesimulator -F/Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Products/Debug-iphonesimulator -filelist /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/Arcane.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/Arcane.swiftmodule -miphoneos-version-min=8.0 -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -Xlinker -dependency_info -Xlinker /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Intermediates/Arcane.build/Debug-iphonesimulator/Arcane.build/Objects-normal/x86_64/Arcane_dependency_info.dat -o /Users/gok2/Library/Developer/Xcode/DerivedData/Arcane-fthukrtpkglaxohiybucxhjwxmkj/Build/Products/Debug-iphonesimulator/Arcane.app/Arcane
  ld: framework not found Fabric for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
- exit 1
  Command /bin/sh failed with exit code 1

**Comment by johnno1962** [comment]
Hi, "If it's necessary to link the framework with another framework copy the contents of the ~/bin/unhide.sh script into the "Run Script" build phase and edit the command that re-links the framework."
