### ISSUE TITLE
Cat "$LINK_FILE_LIST": argument list too long

### ISSUE THREAD

**Issue by ChenLime** [johnno1962/unhide#4]
I have a huge "$LINK_FILE_LIST" file. When Xcode run the script, I got the "argument list too long" issue. How can I fix it?

**Comment by johnno1962** [comment]
Hi, I’ve changed unhide to read the "$LINK_FILE_LIST" internally. Can you pull the project and try again?

**Comment by ChenLime** [comment]
> Hi, I’ve changed unhide to read the "$LINK_FILE_LIST" internally. Can you pull the project and try again?

It works! Appreciate it.

**Comment by johnno1962** [comment]
np
