### ISSUE TITLE
unhide: Could not read .build/Objects-normal/x86_64/TestViewController.o

### ISSUE THREAD

**Issue by spnkr** [johnno1962/unhide#5]
I get `unhide: Could not read /Users/username/Library/Developer/Xcode/DerivedData/sdk2-fknlbuuwguideydtewztbqmyswef/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyApplication.build/Objects-normal/x86_64/TestViewController.o` errors randomly. unhide works great, until it starts throwing these. i then remove the build phase run script, and the error goes away.

Any ideas what could be causing this? How can I help debug this?

Am I using `-Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs` correctly?

```swift
+ '[' Debug = Debug ']'
+ UNHIDE_LDFLAGS=
+ NORMAL_ARCH_FILE=/Users/username/Library/Developer/Xcode/DerivedData/sdk2-fknlbuuwguideydtewztbqmyswef/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyApplication.build/Objects-normal/x86_64/MyApplication
+ LINK_FILE_LIST=/Users/username/Library/Developer/Xcode/DerivedData/sdk2-fknlbuuwguideydtewztbqmyswef/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyApplication.build/Objects-normal/x86_64/MyApplication.LinkFileList
+ [[ /Users/username/Library/Developer/Xcode/DerivedData/sdk2-fknlbuuwguideydtewztbqmyswef/Build/Products/Debug-iphonesimulator/MyApplication.app =~ \.framework ]]
+ VERSIONS='-Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs'
+ echo 'Exporting any "hidden" Swift internal symbols in MyApplication framework'
Exporting any "hidden" Swift internal symbols in MyApplication framework
++ dirname /Users/username/bin/unhide.sh
+ /Users/username/bin/unhide MyApplication /Users/username/Library/Developer/Xcode/DerivedData/sdk2-fknlbuuwguideydtewztbqmyswef/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyApplication.build/Objects-normal/x86_64/MyApplication.LinkFileList
unhide: Could not read /Users/username/Library/Developer/Xcode/DerivedData/sdk2-fknlbuuwguideydtewztbqmyswef/Build/Intermediates.noindex/MyProject.build/Debug-iphonesimulator/MyApplication.build/Objects-normal/x86_64/TestViewController.o
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by spnkr** [comment]
here's my build phase run script:

![image](https://user-images.githubusercontent.com/11250/95009490-7cdbc680-05f0-11eb-88aa-f00549702153.png)

**Comment by johnno1962** [comment]
Hi @spnkr, thanks for the screenshot otherwise this would indeed have been a mystery. I looks like the problem is the unhide build phase needs to go after the compilation phase or the object files may not exist. Ideally it would go after compilation but before linking but this is not possible in Xcode so you have to add it after linking. I've updated the InjectionIII README.
