### ISSUE TITLE
duplicate symbols for architecture x86_64

### ISSUE THREAD

**Issue by GG526** [johnno1962/unhide#6]
error: `duplicate symbol 'default argument`

```

 public func scroll(to page: Int, animated: Bool, completion: ((Bool) -> Void)? = nil) {}
```

```
 public func update(colors: [UIColor], locations: [Double] = [0, 1]) {}
```

A large number of default parameter errors.

![截屏_2021-08-23_17-41-45](https://user-images.githubusercontent.com/11623029/130426270-71142e62-f09d-4e21-a540-efb4c63d1554.jpg)

**Comment by johnno1962** [comment]
Hi, are you using the a newer version of InjectionIII from the releasees https://github.com/johnno1962/InjectionIII/releases? If so you should remove the running of unhide.sh from your project as it has been integrated into the app.

**Comment by GG526** [comment]
My Injection version is 2.9.3, but an error is reported.
```
💉 ⚠️ dlopen() error: dlopen(/Users/lan/Library/Developer/CoreSimulator/Devices/27ADF116-80F9-4AD1-8ACD-B190FCAAAC89/data/Containers/Data/Application/BBBC47DF-BAE5-44B8-8BA6-7BCD75B95703/tmp/eval101.dylib, 2): Symbol not found: _$s12YWQDIOSUIKit13QDDefaultViewCMn
```

**Comment by johnno1962** [comment]
Better. Have you r tried re-running and trying again? These symbols are only "unhidden" after the second build.

**Comment by GG526** [comment]
The rebuild still exists, does it matter that my project uses Cocoapods and uses use_Modular_headers?

**Comment by johnno1962** [comment]
I can TeamView if you like. Send details to githhub at johnholdsworh.com.

**Comment by GG526** [comment]
I am very sorry that TeamView is not allowed.

**Comment by johnno1962** [comment]
Try a clean build then build, inject, build again and re-try the inject.

**Comment by GG526** [comment]
None of the Settings seem to work for me.

**Comment by johnno1962** [comment]
How do you mean? What exactly is the problem/error at the moment?

**Comment by GG526** [comment]
This error occurs when a statically linked library in Cocopods is involved.

```
💉 Loading .dylib ...
💉 Loading .dylib has failed, This is likely because Swift code being injected refers to a function with a default argument. Rebuilding and re-running your project (without a build clean) can resolve this.
💉 ⚠️ dlopen() error: dlopen(/Users/lan/Library/Developer/CoreSimulator/Devices/27ADF116-80F9-4AD1-8ACD-B190FCAAAC89/data/Containers/Data/Application/4E3FD866-2E5D-4D1E-AB6A-C6A35D689364/tmp/eval101.dylib, 2): Symbol not found: _$s12YWQDIOSUIKit13QDDefaultViewCMn
```

**Comment by johnno1962** [comment]
Aha, thanks, that narrows it down. The problem here is that symbols like this are "hidden" i.e. it can be linked against but not dynamically linked against which causes the injection dylib to fail to load. There is code in Injection to "unhide" these symbols but it seems to not cover statically linked libraries for some reason. I'd need to see your project to be able to tell you more.

**Comment by GG526** [comment]
The current file is not associated with any other static libraries.


```
💉 Loading .dylib ...
💉 Loaded .dylib - Ignore any duplicate class warning ^
💉 Injected class 'xx.QDInjectionView'
```

**Comment by GG526** [comment]
> Aha, thanks, that narrows it down. The problem here is that symbols like this are "hidden" i.e. it can be linked against but not dynamically linked against which causes the injection dylib to fail to load. There is code in Injection to "unhide" these symbols but it seems to not cover statically linked libraries for some reason. I'd need to see your project to be able to tell you more.

I'm sorry I don't have permission to do this for the company project

**Comment by GG526** [comment]
![image](https://user-images.githubusercontent.com/11623029/130607786-023ca67b-2244-4a70-a120-0612f1a31573.png)
![image](https://user-images.githubusercontent.com/11623029/130607839-616cf7bc-3508-4fb2-87cd-fe1d89bf2da1.png)

Here are some Settings for Cocopods.

**Comment by GG526** [comment]
![image](https://user-images.githubusercontent.com/11623029/130608049-dffc55fb-a78b-449b-8d20-cbe0f7b475c6.png)

**Comment by GG526** [comment]
The test interface written in the project is not associated with any libraries but does not report errors.

```

import Foundation

class QDInjectionView: UIView {
    
    //MARK: - typealias
    
    //MARK: - storage
    
    //MARK: - lazy
    
    //MARK: - calculate
    
    //MARK: - init
    override init(frame: CGRect) {
        super.init(frame: frame)
        layout()
    }
    
    init() {
        super.init(frame: CGRect.zero)
        a()
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    //MARK: - deinit
    
    //MARK: - override
    
    //MARK: - layout
    private func layout() {
        let label = UILabel()
        label.text = "1223"
        addSubview(label)
        a()
    }
    
    private func a(_ b: Int = 0, c: Int = 2) {
        b + c
    }
    
    //MARK: - public function
    
    //MARK: - private function
}

```

**Comment by johnno1962** [comment]
It's difficult to say particularly with cocoa pods. I can only provide yo with more information about what InjectionII does internally. When you inject it scans the "DerivedData" for a project looking for .linkFileList files which list the object files and "unhides" various problemattic symbols such as this which are linked into your app the next time you build. I don't know if this works. the way your pods are set up but this is what to look out for.

**Comment by GG526** [comment]
I tried to change some compilation Settings but nothing worked. Any good ideas? Recompile of our project is very slow and requires Injection

**Comment by johnno1962** [comment]
Ask who you need to if they can sanction the use of TeamView for half an hour. I've done this many times before.

**Comment by GG526** [comment]
I see that the filelist under the tem directory is Compile Sources. I wonder how to mask some framework or `.a ` file verification.

**Comment by johnno1962** [comment]
If TeamView is not an option what about a hangout where I don't have remote control but can learn more about your project setup. Is this problem affecting all injections or only a particular file? If so, you may not be able to inject that particular file.

**Comment by GG526** [comment]
I can use hangout, but I haven't used it and don't know how to add you. Is it a Google account?

**Comment by GG526** [comment]
The Exported Symbols File is configured in the debug environment while optimizing the package size.

**Comment by GG526** [comment]
> The Exported Symbols File is configured in the debug environment while optimizing the package size.

**Comment by johnno1962** [comment]
So you found a solution? To use a framework instead on a static library in the Podfile?

**Comment by GG526** [comment]
> So you found a solution? To use a framework instead on a static library in the Podfile?

static library.

**Comment by GG526** [comment]
The `Exported Symbols File` has other options configured in the debug environment. This error has nothing to do with the configuration items in the profile
